name: plbufr
channels:
- conda-forge
- nodefaults
dependencies:
- attrs
- pip
- numpy
- polars
- geopolars
- make
- mypy
- myst-parser
- pre-commit
- pydata-sphinx-theme
- pytest
- pytest-cov
- sphinx
- sphinx_rtd_theme
- sphinxcontrib-apidoc
- nbformat
- nbconvert
- nbsphinx
- ipykernel
